"""Change description to Text

Revision ID: bbac296e3aa0
Revises: 2e387503d833
Create Date: 2025-10-28 18:19:16.776699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbac296e3aa0'
down_revision: Union[str, Sequence[str], None] = '2e387503d833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breed', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('pets_breed_id_fkey'), 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'breed', ['breed_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key(op.f('pets_breed_id_fkey'), 'pets', 'breed', ['breed_id'], ['id'])
    op.alter_column('breed', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
